version: '3.8'

networks:
  default:
    driver: bridge
    name: ${DCAPE_NET}
    driver_opts:
      com.docker.network.bridge.name: ${DCAPE_NET}
    ipam:
      config:
        - subnet: ${DCAPE_SUBNET}

  intra:
    driver: bridge
    internal: true
    name: ${DCAPE_NET_INTRA}
    driver_opts:
      com.docker.network.bridge.name: ${DCAPE_NET_INTRA}
    ipam:
      config:
        - subnet: ${DCAPE_SUBNET_INTRA}

services:

  # ------------------------------------------------------------------------------
  db:
    image: ${PG_IMAGE}
    restart: always
    networks:
      - default
      - intra
    ports:
      - "127.0.0.1:${PG_PORT_LOCAL}:5432"
    labels:
      - "traefik.enable=false"
    environment:
      - POSTGRES_PASSWORD=${PG_DB_PASS}
      - TZ=${TZ}
      - LANG=${PG_ENCODING}
      - DCAPE_DB_DUMP_DEST=/opt/backup
    volumes:
      - ./${DCAPE_VAR}/db/data:/var/lib/postgresql/data
      - ./${DCAPE_VAR}/db/backup:/opt/backup
      - ./${DCAPE_VAR}/db/conf.d:/opt/conf.d
      - ./${DCAPE_VAR}/db/shared:/opt/shared
      - ./${DCAPE_VAR}/db/init:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres", "-h", "db"]
      interval: 2s
      timeout: 3s
      retries: 3
    shm_size: ${PG_SHM_SIZE}
    stop_grace_period: 5s
    stop_signal: SIGINT
